### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Arkni** [Arkni/changelog-generator#1]
- [x] Exit when there is no commit (this happens if you run it inside a repo that has no commits after the latest tag) (Fixed in 3ca1ee6)
- [x] ~~Append the changelog to `CHANGELOG(.md)` file (make it an option, maybe exit with error  or create it when the file doesn't exist)~~ **Nah, it's not a good idea (can get really costly by the time)**
- [x] ~~Update `jquery` preset in order to include the commit hashs in changelog~~ (no need for it ... for now)
- [x] Support more presets
- [x] Improve execution speed (Fixed in 3ca1ee6, now it's 2x faster than before)

**Comment by wbruno** [comment]
@Arkni I've added one preset at https://github.com/Arkni/changelog-generator/pull/2

**Comment by wbruno** [comment]
about the append to CHANGELOG.md, you can just put this line on wiki:

```
 echo -e "$(changelog -p node)\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
```

**Comment by Arkni** [comment]
When I first created this TODO list, I thought I can add an option to this cli that append the resulting changelog to `CHANGELOG.md` using only JavaScript (`fs` ...).

The idea was, moving the content of existing `Changelog` file to a `tmp` file and replace existing `Changelog` entirely with new content. And then append the content of `tmp` to `Changelog`, but that can get costly by the time.

I'll add your command to `Examples` section. Thanks :)

**Comment by Arkni** [comment]
270a185 :)

**Comment by Arkni** [comment]
We now have 3 presets: `grunt`, `jquery` and `node`
